services:
  app:
    image: budgetbeast:latest
    volumes:
      - ./config/docker.yaml:/app/config.yaml
      - ./config/sa_key.json:/app/sa_key.json
    ports:
      - "3333:3333"
    environment:
      - RUST_LOG=info